
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/Hubert/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:207 (message)"
      - "CMakeLists.txt:28 (project)"
    message: |
      The target system is: Generic -  - arm
      The host system is: Windows - 10.0.26200 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Users/Hubert/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-4.2/Modules/CMakeNinjaFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:28 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Program used to build from build.ninja files."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "ninja-build"
      - "ninja"
      - "samu"
    candidate_directories:
      - "C:/Users/Hubert/AppData/Local/Programs/cursor/resources/app/resources/helpers/"
      - "C:/Program Files (x86)/STMicroelectronics/stlink_server/"
      - "C:/Users/Hubert/%STM32CLT_PATH%/"
      - "C:/Users/Hubert/%STM32CLT_PATH%/CMake/bin/"
      - "C:/Users/Hubert/%STM32CLT_PATH%/st-arm-clang/bin/"
      - "C:/Users/Hubert/%STM32CLT_PATH%/Ninja/bin/"
      - "C:/Users/Hubert/%STM32CLT_PATH%/GNU-tools-for-STM32/bin/"
      - "C:/Users/Hubert/%STM32CLT_PATH%/STLink-gdb-server/bin/"
      - "C:/Users/Hubert/%STM32CLT_PATH%/STM32CubeProgrammer/bin/"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "C:/Program Files/dotnet/"
      - "C:/Program Files/Git/cmd/"
      - "C:/Program Files/Docker/Docker/resources/bin/"
      - "C:/Users/Hubert/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/Hubert/AppData/Local/JetBrains/Toolbox/scripts/"
      - "C:/Users/Hubert/.dotnet/tools/"
      - "C:/Users/Hubert/AppData/Local/Programs/cursor/resources/app/bin/"
    searched_directories:
      - "C:/Users/Hubert/AppData/Local/Programs/cursor/resources/app/resources/helpers/ninja-build.com"
      - "C:/Users/Hubert/AppData/Local/Programs/cursor/resources/app/resources/helpers/ninja-build.exe"
      - "C:/Users/Hubert/AppData/Local/Programs/cursor/resources/app/resources/helpers/ninja-build"
      - "C:/Users/Hubert/AppData/Local/Programs/cursor/resources/app/resources/helpers/ninja.com"
      - "C:/Users/Hubert/AppData/Local/Programs/cursor/resources/app/resources/helpers/ninja.exe"
      - "C:/Users/Hubert/AppData/Local/Programs/cursor/resources/app/resources/helpers/ninja"
      - "C:/Users/Hubert/AppData/Local/Programs/cursor/resources/app/resources/helpers/samu.com"
      - "C:/Users/Hubert/AppData/Local/Programs/cursor/resources/app/resources/helpers/samu.exe"
      - "C:/Users/Hubert/AppData/Local/Programs/cursor/resources/app/resources/helpers/samu"
      - "C:/Program Files (x86)/STMicroelectronics/stlink_server/ninja-build.com"
      - "C:/Program Files (x86)/STMicroelectronics/stlink_server/ninja-build.exe"
      - "C:/Program Files (x86)/STMicroelectronics/stlink_server/ninja-build"
      - "C:/Program Files (x86)/STMicroelectronics/stlink_server/ninja.com"
      - "C:/Program Files (x86)/STMicroelectronics/stlink_server/ninja.exe"
      - "C:/Program Files (x86)/STMicroelectronics/stlink_server/ninja"
      - "C:/Program Files (x86)/STMicroelectronics/stlink_server/samu.com"
      - "C:/Program Files (x86)/STMicroelectronics/stlink_server/samu.exe"
      - "C:/Program Files (x86)/STMicroelectronics/stlink_server/samu"
      - "C:/Users/Hubert/%STM32CLT_PATH%/ninja-build.com"
      - "C:/Users/Hubert/%STM32CLT_PATH%/ninja-build.exe"
      - "C:/Users/Hubert/%STM32CLT_PATH%/ninja-build"
      - "C:/Users/Hubert/%STM32CLT_PATH%/ninja.com"
      - "C:/Users/Hubert/%STM32CLT_PATH%/ninja.exe"
      - "C:/Users/Hubert/%STM32CLT_PATH%/ninja"
      - "C:/Users/Hubert/%STM32CLT_PATH%/samu.com"
      - "C:/Users/Hubert/%STM32CLT_PATH%/samu.exe"
      - "C:/Users/Hubert/%STM32CLT_PATH%/samu"
      - "C:/Users/Hubert/%STM32CLT_PATH%/CMake/bin/ninja-build.com"
      - "C:/Users/Hubert/%STM32CLT_PATH%/CMake/bin/ninja-build.exe"
      - "C:/Users/Hubert/%STM32CLT_PATH%/CMake/bin/ninja-build"
      - "C:/Users/Hubert/%STM32CLT_PATH%/CMake/bin/ninja.com"
      - "C:/Users/Hubert/%STM32CLT_PATH%/CMake/bin/ninja.exe"
      - "C:/Users/Hubert/%STM32CLT_PATH%/CMake/bin/ninja"
      - "C:/Users/Hubert/%STM32CLT_PATH%/CMake/bin/samu.com"
      - "C:/Users/Hubert/%STM32CLT_PATH%/CMake/bin/samu.exe"
      - "C:/Users/Hubert/%STM32CLT_PATH%/CMake/bin/samu"
      - "C:/Users/Hubert/%STM32CLT_PATH%/st-arm-clang/bin/ninja-build.com"
      - "C:/Users/Hubert/%STM32CLT_PATH%/st-arm-clang/bin/ninja-build.exe"
      - "C:/Users/Hubert/%STM32CLT_PATH%/st-arm-clang/bin/ninja-build"
      - "C:/Users/Hubert/%STM32CLT_PATH%/st-arm-clang/bin/ninja.com"
      - "C:/Users/Hubert/%STM32CLT_PATH%/st-arm-clang/bin/ninja.exe"
      - "C:/Users/Hubert/%STM32CLT_PATH%/st-arm-clang/bin/ninja"
      - "C:/Users/Hubert/%STM32CLT_PATH%/st-arm-clang/bin/samu.com"
      - "C:/Users/Hubert/%STM32CLT_PATH%/st-arm-clang/bin/samu.exe"
      - "C:/Users/Hubert/%STM32CLT_PATH%/st-arm-clang/bin/samu"
      - "C:/Users/Hubert/%STM32CLT_PATH%/Ninja/bin/ninja-build.com"
      - "C:/Users/Hubert/%STM32CLT_PATH%/Ninja/bin/ninja-build.exe"
      - "C:/Users/Hubert/%STM32CLT_PATH%/Ninja/bin/ninja-build"
      - "C:/Users/Hubert/%STM32CLT_PATH%/Ninja/bin/ninja.com"
      - "C:/Users/Hubert/%STM32CLT_PATH%/Ninja/bin/ninja.exe"
      - "C:/Users/Hubert/%STM32CLT_PATH%/Ninja/bin/ninja"
      - "C:/Users/Hubert/%STM32CLT_PATH%/Ninja/bin/samu.com"
      - "C:/Users/Hubert/%STM32CLT_PATH%/Ninja/bin/samu.exe"
      - "C:/Users/Hubert/%STM32CLT_PATH%/Ninja/bin/samu"
      - "C:/Users/Hubert/%STM32CLT_PATH%/GNU-tools-for-STM32/bin/ninja-build.com"
      - "C:/Users/Hubert/%STM32CLT_PATH%/GNU-tools-for-STM32/bin/ninja-build.exe"
      - "C:/Users/Hubert/%STM32CLT_PATH%/GNU-tools-for-STM32/bin/ninja-build"
      - "C:/Users/Hubert/%STM32CLT_PATH%/GNU-tools-for-STM32/bin/ninja.com"
      - "C:/Users/Hubert/%STM32CLT_PATH%/GNU-tools-for-STM32/bin/ninja.exe"
      - "C:/Users/Hubert/%STM32CLT_PATH%/GNU-tools-for-STM32/bin/ninja"
      - "C:/Users/Hubert/%STM32CLT_PATH%/GNU-tools-for-STM32/bin/samu.com"
      - "C:/Users/Hubert/%STM32CLT_PATH%/GNU-tools-for-STM32/bin/samu.exe"
      - "C:/Users/Hubert/%STM32CLT_PATH%/GNU-tools-for-STM32/bin/samu"
      - "C:/Users/Hubert/%STM32CLT_PATH%/STLink-gdb-server/bin/ninja-build.com"
      - "C:/Users/Hubert/%STM32CLT_PATH%/STLink-gdb-server/bin/ninja-build.exe"
      - "C:/Users/Hubert/%STM32CLT_PATH%/STLink-gdb-server/bin/ninja-build"
      - "C:/Users/Hubert/%STM32CLT_PATH%/STLink-gdb-server/bin/ninja.com"
      - "C:/Users/Hubert/%STM32CLT_PATH%/STLink-gdb-server/bin/ninja.exe"
      - "C:/Users/Hubert/%STM32CLT_PATH%/STLink-gdb-server/bin/ninja"
      - "C:/Users/Hubert/%STM32CLT_PATH%/STLink-gdb-server/bin/samu.com"
      - "C:/Users/Hubert/%STM32CLT_PATH%/STLink-gdb-server/bin/samu.exe"
      - "C:/Users/Hubert/%STM32CLT_PATH%/STLink-gdb-server/bin/samu"
      - "C:/Users/Hubert/%STM32CLT_PATH%/STM32CubeProgrammer/bin/ninja-build.com"
      - "C:/Users/Hubert/%STM32CLT_PATH%/STM32CubeProgrammer/bin/ninja-build.exe"
      - "C:/Users/Hubert/%STM32CLT_PATH%/STM32CubeProgrammer/bin/ninja-build"
      - "C:/Users/Hubert/%STM32CLT_PATH%/STM32CubeProgrammer/bin/ninja.com"
      - "C:/Users/Hubert/%STM32CLT_PATH%/STM32CubeProgrammer/bin/ninja.exe"
      - "C:/Users/Hubert/%STM32CLT_PATH%/STM32CubeProgrammer/bin/ninja"
      - "C:/Users/Hubert/%STM32CLT_PATH%/STM32CubeProgrammer/bin/samu.com"
      - "C:/Users/Hubert/%STM32CLT_PATH%/STM32CubeProgrammer/bin/samu.exe"
      - "C:/Users/Hubert/%STM32CLT_PATH%/STM32CubeProgrammer/bin/samu"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/ninja-build.com"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/ninja-build.exe"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/ninja-build"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/ninja.com"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/ninja.exe"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/ninja"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/samu.com"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/samu.exe"
      - "C:/Program Files/Common Files/Oracle/Java/javapath/samu"
      - "C:/Windows/System32/ninja-build.com"
      - "C:/Windows/System32/ninja-build.exe"
      - "C:/Windows/System32/ninja-build"
      - "C:/Windows/System32/ninja.com"
      - "C:/Windows/System32/ninja.exe"
      - "C:/Windows/System32/ninja"
      - "C:/Windows/System32/samu.com"
      - "C:/Windows/System32/samu.exe"
      - "C:/Windows/System32/samu"
      - "C:/Windows/ninja-build.com"
      - "C:/Windows/ninja-build.exe"
      - "C:/Windows/ninja-build"
      - "C:/Windows/ninja.com"
      - "C:/Windows/ninja.exe"
      - "C:/Windows/ninja"
      - "C:/Windows/samu.com"
      - "C:/Windows/samu.exe"
      - "C:/Windows/samu"
      - "C:/Windows/System32/wbem/ninja-build.com"
      - "C:/Windows/System32/wbem/ninja-build.exe"
      - "C:/Windows/System32/wbem/ninja-build"
      - "C:/Windows/System32/wbem/ninja.com"
      - "C:/Windows/System32/wbem/ninja.exe"
      - "C:/Windows/System32/wbem/ninja"
      - "C:/Windows/System32/wbem/samu.com"
      - "C:/Windows/System32/wbem/samu.exe"
      - "C:/Windows/System32/wbem/samu"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja-build"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/ninja"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/samu"
      - "C:/Windows/System32/OpenSSH/ninja-build.com"
      - "C:/Windows/System32/OpenSSH/ninja-build.exe"
      - "C:/Windows/System32/OpenSSH/ninja-build"
      - "C:/Windows/System32/OpenSSH/ninja.com"
      - "C:/Windows/System32/OpenSSH/ninja.exe"
      - "C:/Windows/System32/OpenSSH/ninja"
      - "C:/Windows/System32/OpenSSH/samu.com"
      - "C:/Windows/System32/OpenSSH/samu.exe"
      - "C:/Windows/System32/OpenSSH/samu"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja-build.com"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja-build.exe"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja-build"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja.com"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja.exe"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/ninja"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/samu.com"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/samu.exe"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/samu"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja-build.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja-build.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja-build"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/ninja"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/samu.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/samu.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/samu"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja-build"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ninja"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/samu"
      - "C:/Program Files/dotnet/ninja-build.com"
      - "C:/Program Files/dotnet/ninja-build.exe"
      - "C:/Program Files/dotnet/ninja-build"
      - "C:/Program Files/dotnet/ninja.com"
      - "C:/Program Files/dotnet/ninja.exe"
      - "C:/Program Files/dotnet/ninja"
      - "C:/Program Files/dotnet/samu.com"
      - "C:/Program Files/dotnet/samu.exe"
      - "C:/Program Files/dotnet/samu"
      - "C:/Program Files/Git/cmd/ninja-build.com"
      - "C:/Program Files/Git/cmd/ninja-build.exe"
      - "C:/Program Files/Git/cmd/ninja-build"
      - "C:/Program Files/Git/cmd/ninja.com"
      - "C:/Program Files/Git/cmd/ninja.exe"
      - "C:/Program Files/Git/cmd/ninja"
      - "C:/Program Files/Git/cmd/samu.com"
      - "C:/Program Files/Git/cmd/samu.exe"
      - "C:/Program Files/Git/cmd/samu"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja-build.com"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja-build.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja-build"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja.com"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/ninja"
      - "C:/Program Files/Docker/Docker/resources/bin/samu.com"
      - "C:/Program Files/Docker/Docker/resources/bin/samu.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/samu"
      - "C:/Users/Hubert/AppData/Local/Microsoft/WindowsApps/ninja-build.com"
      - "C:/Users/Hubert/AppData/Local/Microsoft/WindowsApps/ninja-build.exe"
      - "C:/Users/Hubert/AppData/Local/Microsoft/WindowsApps/ninja-build"
      - "C:/Users/Hubert/AppData/Local/Microsoft/WindowsApps/ninja.com"
      - "C:/Users/Hubert/AppData/Local/Microsoft/WindowsApps/ninja.exe"
      - "C:/Users/Hubert/AppData/Local/Microsoft/WindowsApps/ninja"
      - "C:/Users/Hubert/AppData/Local/Microsoft/WindowsApps/samu.com"
      - "C:/Users/Hubert/AppData/Local/Microsoft/WindowsApps/samu.exe"
      - "C:/Users/Hubert/AppData/Local/Microsoft/WindowsApps/samu"
      - "C:/Users/Hubert/AppData/Local/JetBrains/Toolbox/scripts/ninja-build.com"
      - "C:/Users/Hubert/AppData/Local/JetBrains/Toolbox/scripts/ninja-build.exe"
      - "C:/Users/Hubert/AppData/Local/JetBrains/Toolbox/scripts/ninja-build"
      - "C:/Users/Hubert/AppData/Local/JetBrains/Toolbox/scripts/ninja.com"
      - "C:/Users/Hubert/AppData/Local/JetBrains/Toolbox/scripts/ninja.exe"
      - "C:/Users/Hubert/AppData/Local/JetBrains/Toolbox/scripts/ninja"
      - "C:/Users/Hubert/AppData/Local/JetBrains/Toolbox/scripts/samu.com"
      - "C:/Users/Hubert/AppData/Local/JetBrains/Toolbox/scripts/samu.exe"
      - "C:/Users/Hubert/AppData/Local/JetBrains/Toolbox/scripts/samu"
      - "C:/Users/Hubert/.dotnet/tools/ninja-build.com"
      - "C:/Users/Hubert/.dotnet/tools/ninja-build.exe"
      - "C:/Users/Hubert/.dotnet/tools/ninja-build"
      - "C:/Users/Hubert/.dotnet/tools/ninja.com"
      - "C:/Users/Hubert/.dotnet/tools/ninja.exe"
      - "C:/Users/Hubert/.dotnet/tools/ninja"
      - "C:/Users/Hubert/.dotnet/tools/samu.com"
      - "C:/Users/Hubert/.dotnet/tools/samu.exe"
      - "C:/Users/Hubert/.dotnet/tools/samu"
      - "C:/Users/Hubert/AppData/Local/Programs/cursor/resources/app/bin/ninja-build.com"
      - "C:/Users/Hubert/AppData/Local/Programs/cursor/resources/app/bin/ninja-build.exe"
      - "C:/Users/Hubert/AppData/Local/Programs/cursor/resources/app/bin/ninja-build"
      - "C:/Users/Hubert/AppData/Local/Programs/cursor/resources/app/bin/ninja.com"
      - "C:/Users/Hubert/AppData/Local/Programs/cursor/resources/app/bin/ninja.exe"
      - "C:/Users/Hubert/AppData/Local/Programs/cursor/resources/app/bin/ninja"
      - "C:/Users/Hubert/AppData/Local/Programs/cursor/resources/app/bin/samu.com"
      - "C:/Users/Hubert/AppData/Local/Programs/cursor/resources/app/bin/samu.exe"
      - "C:/Users/Hubert/AppData/Local/Programs/cursor/resources/app/bin/samu"
    found: false
    search_context:
      ENV{PATH}:
        - "c:\\Users\\Hubert\\AppData\\Local\\Programs\\cursor\\resources\\app\\resources\\helpers"
        - "C:\\Program Files (x86)\\STMicroelectronics\\stlink_server"
        - "%STM32CLT_PATH%"
        - "%STM32CLT_PATH%\\CMake\\bin"
        - "%STM32CLT_PATH%\\st-arm-clang\\bin"
        - "%STM32CLT_PATH%\\Ninja\\bin"
        - "%STM32CLT_PATH%\\GNU-tools-for-STM32\\bin"
        - "%STM32CLT_PATH%\\STLink-gdb-server\\bin"
        - "%STM32CLT_PATH%\\STM32CubeProgrammer\\bin"
        - "C:\\Program Files\\Common Files\\Oracle\\Java\\javapath"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA App\\NvDLISR"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\Docker\\Docker\\resources\\bin"
        - "C:\\Users\\Hubert\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\Hubert\\AppData\\Local\\JetBrains\\Toolbox\\scripts"
        - "C:\\Users\\Hubert\\.dotnet\\tools"
        - "C:\\Users\\Hubert\\AppData\\Local\\Programs\\cursor\\resources\\app\\bin"
...
